import os
from pathlib import Path

from pyrogram import Client


def main() -> None:
    api_id_raw = os.getenv("VC_API_ID") or os.getenv("API_ID") or input("Enter API_ID: ").strip()
    api_hash = os.getenv("VC_API_HASH") or os.getenv("API_HASH") or input("Enter API_HASH: ").strip()

    if not api_id_raw.isdigit():
        raise SystemExit("API_ID must be numeric.")
    if not api_hash:
        raise SystemExit("API_HASH is required.")

    api_id = int(api_id_raw)
    session_name = "assistant_session_generator"

    print("\nOpening Pyrogram login flow...")
    print("Telegram will ask for phone number, OTP and 2FA (if enabled).\n")

    with Client(session_name, api_id=api_id, api_hash=api_hash, workdir=str(Path.cwd())) as app:
        session_string = app.export_session_string()

    print("\nASSISTANT_SESSION (put this exact value in Railway env):")
    print(session_string)

    # Clean local session files generated by the helper.
    for path in Path.cwd().glob(f"{session_name}.session*"):
        try:
            path.unlink(missing_ok=True)
        except Exception:
            pass


if __name__ == "__main__":
    main()
